name: ZombieIsland
version: ${project.version}
main: xyz.yarinlevi.zombieisland.ZombieIsland
api-version: 1.16
depend:
  - AureliumSkills
  - NBTAPI

commands:
  testmessages:
    permission: op
  zidebug:
    permission: zombieisland.admin.debug
  ziadmin:
    permission: zombieisland.admin
  ziswords:
    permission: zombieisland.admin.swords

permissions:
  op:
    default: op