name: ZombieIsland
version: ${project.version}
main: xyz.yarinlevi.zombieisland.ZombieIsland
api-version: 1.16
depend:
  - QAureliumSkills
  - NBTAPI
  - MythicMobs

commands:
  testmessages:
    permission: zombieisland.admin.debug.messages
  zidebug:
    permission: zombieisland.admin.debug
  ziadmin:
    permission: zombieisland.admin
  ziswords:
    permission: zombieisland.admin.swords
  zipoints:
    permission: zombieisland.admin.points