Prefix: "&4&lZombieIsland >> &r"


# ZombieIsland Swords #
#In seconds (No half seconds):
kopaka_slowness_duration: 5
kopaka_slowness_amplifier: 1
poisonWand_poison_duration: 3
poisonWand_poison_amplifier: 4
Fire_Sword_Burn: 3

# SWORD NAMES:
StormBreaker: "&6STORMBREAKER"
FireSword: "&cFireSword"
Kopaka: "&fKopaka"
PoisonWand: "&2&lPoison Blade"

# Materials (Items, eg: DIAMOND_SWORD)
StormBreaker_Item: DIAMOND_SWORD
Kopaka_Item: IRON_SWORD
FireSword_Item: STONE_SWORD
PoisonWand_Item: GOLDEN_SWORD

# Spawner Settings #
MobLimitPerChunk: 4
# How long per mob spawn? (In seconds)
SpawnerRate: 3


# ~ Config Version: 0.0.4 ~ #