name: ZombieIsland
version: 0.2.4-EXPERIMENTAL
main: xyz.yarinlevi.zombieisland.ZombieIsland
api-version: 1.16
depend:
  - AureliumSkills

commands:
  testmessages:
    permission: op
  zidebug:
    permission: zombieisland.admin.debug
  ziadmin:
    permission: zombieisland.admin
  ziswords:
    permission: zombieisland.admin.swords

permissions:
  op:
    default: op